FROM 654654287954.dkr.ecr.us-west-2.amazonaws.com/makethejump/python-base:sha256:321d639c480144ef3a19eadb82813f6606676702

# Copy function code and dependencies
COPY server.py  .
COPY hf_logic.py  .
COPY lambda-entrypoint.sh /lambda-entrypoint.sh
RUN chmod +x /lambda-entrypoint.sh

# Set the entrypoint to use the Lambda Runtime Interface Client
ENTRYPOINT ["/lambda-entrypoint.sh"]
